CREATE DATABASE avaliacao;

CREATE TABLE IF NOT EXISTS notas(
  id notas INT  AUTO_INCREMENT,
  FK_funcionario INT,
  notas INT
);


CREATE TABLE IF NOT EXISTS `funcionario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(25),
  `nascimento` DATE,
  `Setor` VARCHAR(255) NOT NULL,
  `funcao` VARCHAR(255) NOT NULL,
  `email` VARCHAR(150),
  `situacao` VARCHAR(15),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;



INSERT INTO funcionario VALUES(NULL,'AGOSTINHO MARIANO DA  SILVA','49-99809-1809','1959-01-05', 'RECEPCAO','MENSAGEIRO', 'NULL', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'ALEXANDRE FRANCISCO LOHMANN VARGAS','9S99038843','1995-12-18', 'RECEPCAO','RECEPCIONISTA', 'NULL', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'ALLAN BARTOLOME','49 8820-9247','1960-12-06', 'RECEPCAO','RECEPCIONISTA', 'allanbartolome@ig.com.br', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'CLAUDINEI CARDOSO ALVES','49988378516','1980-05-05', 'RECEPCAO','MENSAGEIRO', 'dindosc@hotmail.com', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'DANIELA UNTENBERGER','Null','1987-09-06', 'RECEPCAO','RECEPCIONISTA', 'danicauntenberger@gmail.com', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'DILCEU SATICQ','933002085','1968-02-10', 'RECEPCAO','MENSAGEIRO', 'Null', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'DIRCE MARIA STEFFANI','49-99966-1907','1961-03-25', 'RECEPCAO','RECEPCIONISTA', 'dircesteffani@yahoo.com.br', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'ISAIAS BATISTA','49-991845629','1979-12-23', 'RECEPCAO','RECEPCIONISTA', 'isaias@developer.dev.br', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'JOSEMAR SAVENHAGO','49-98197875','1978-11-25', 'RECEPCAO','RECEPCIONISTA', 'josemarsavenhago@hotmail.com', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'NOEMIO TARCISIO SCHIEHL','49-3554-4809','1972-09-20', 'RECEPCAO','RECEPCIONISTA', 'jnoemioschiehl@yahoo.com.br', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'SIDNEY PADILHA DOS SANTOS','35223297','1955-05-29', 'RECEPCAO','MENSAGEIRO', 'Null', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'VALTAIR RIBEIRO','49991740098','1955-05-29', 'RECEPCAO','MENSAGEIRO', 'Null', 'ATIVO');
INSERT INTO funcionario VALUES(NULL,'EDNILSON SANGUANINI','988059494','1971-03-29', 'RECEPCAO','FINANCEIRO', 'Null', 'ATIVO');

 
CREATE TABLE IF NOT EXISTS `AGOSTINHO` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ALEXANDRE` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ALLAN` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `CLAUDINEI` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `DANIELA` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `DILCEU` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `DIRCE` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ISAIAS` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `JOSEMAR` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `TARCISIO` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `SIDNEY` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `VALTAIR` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `EDNILSON` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_funcionario` INT,
  `CONT_ESTOQUE_MAT` INT,
  `CONTROLE_DE_BEBIDAS`INT,
  `ACOMP_CALDEIRA` INT,
  `LIMPEZA_LOCAL_REC_RAMPA` INT,
  `CARRO_C_LIST_INICIAL_CONF` INT,
  `CHAVE_DE_CARRO_ANDAR` INT,
  `PROBLEMA_COM_BAGAGEM` INT,
  `CHECK_LIST_COMUNICACAO` INT,
  `ORG_PRANCHETA` INT,
  `COLABORACAO_COLEGUISMO` INT,
  `CONT_VELOCIDADE_CARRO` INT,
  `SOLUCAO_DE_PROBLEMAS` INT,
  `AJUDA_NA_RECEPCAO_MENSAG` INT,
  `CONFERENCIA_SALAS_REUNIAO` INT,
  `SINISTRO_CARRO` INT,
  `DATA` DATE,
  foreign key(id) references funcionario (id),
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

